-- Setup vim fugitive for git integration

vim.keymap.set("n", "<leader>gp", ":Git push<CR>", { noremap = true })
vim.keymap.set("n", "<leader>gP", ":Git push --force-with-lease<CR>", { noremap = true })
vim.keymap.set("n", "<leader>gu", ":Git pull<CR>", { noremap = true })
vim.keymap.set("n", "<leader>gU", ":Git pull --rebase<CR>", { noremap = true })
vim.keymap.set("n", "<leader>gs", ":G<CR>", { noremap = true })
vim.keymap.set("n", "<leader>gB", ":Git blame<CR>", { noremap = true })
vim.keymap.set("n", "<leader>ds", ":Gdiffsplit<CR>", { noremap = true })
vim.keymap.set("n", "<leader>gj", ":diffget //3<CR>", { noremap = true })
vim.keymap.set("n", "<leader>gf", ":diffget //2<CR>", { noremap = true })
vim.keymap.set("n", "<leader>gF", ":Git fetch --all<CR>", { noremap = true })
vim.keymap.set("n", "<leader>gl", ":Git log<CR>", { noremap = true })
vim.keymap.set("n", "<leader>gS", ":Git stash<CR>", { noremap = true })
vim.keymap.set("n", "<leader>GS", ":Git stash pop<CR>", { noremap = true })
