#!/bin/bash

query=$(echo "" | rofi -dmenu -p "Enter YouTube Search Query:")
MESA_LOADER_DRIVER_OVERRIDE=crocus __EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/50_mesa.json brave --password-store=basic --new-window --incognito "youtube.com/search?q=$query" &
