vim.cmd('syntax on')
 
vim.cmd('set exrc')
vim.cmd('set tabstop=4 softtabstop=4')
vim.cmd('set shiftwidth=4')
vim.cmd('set expandtab')
vim.cmd('set smartindent')
vim.cmd('set nohlsearch')
vim.cmd('set hidden')
vim.cmd('set noerrorbells')
vim.cmd('set nu')
vim.cmd('set relativenumber')
vim.cmd('set nowrap')
vim.cmd('set noswapfile')
vim.cmd('set nobackup')
vim.cmd('set undodir=~/.config/nvim/undodir')
vim.cmd('set undofile')
vim.cmd('set incsearch')
vim.cmd('set termguicolors')
vim.cmd('set scrolloff=8')
vim.cmd('set signcolumn=yes')
vim.cmd('set guicursor=')
vim.cmd('set colorcolumn=80')
vim.cmd('set backspace=indent,eol,start')
vim.cmd('set lazyredraw')
vim.cmd('set ignorecase smartcase')
vim.cmd('set regexpengine=0')
vim.cmd('set diffopt+=vertical')
vim.cmd('set encoding=utf-8')
vim.cmd('set fileencoding=utf-8')
vim.cmd('set termencoding=utf-8')
vim.cmd('set noshowmode')
vim.cmd('set background=dark')

vim.cmd('filetype plugin indent on')